### ISSUE TITLE
Can I debug the script from the browser's dev tools?

### ISSUE THREAD

**Issue by ptatoChi** [wechatjs/vdebugger#2]
Hi thanks for your work.

I was wondering if it's possible to debug the custom scripts inside the browser's dev tool source window

**Comment by Siubaak** [comment]
You can check this repo out, which is a debug toolkit based on chrome devtools and vdebugger. :)

**Comment by Siubaak** [comment]
You can check [mprdev](https://github.com/wechatjs/mprdev) out, which is a debug toolkit based on Chrome Devtools and vdebugger.

Also, you can make your own dev tools based on [Chrome DevTools](https://github.com/ChromeDevTools/devtools-frontend) and [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol), by just implementing the protocols below:

**Comment by Siubaak** [comment]
You can check [mprdev](https://github.com/wechatjs/mprdev) out, which is a debug toolkit based on Chrome Devtools and vdebugger.

Also, you can use vdebugger to make your own script debug tools based on [Chrome DevTools](https://github.com/ChromeDevTools/devtools-frontend) and [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol), by just implementing the protocols below:

- Debugger.enable
- Debugger.getScriptSource
- Debugger.evaluateOnCallFrame
- Debugger.getPossibleBreakpoints
- Debugger.setPauseOnExceptions
- Debugger.setBreakpointsActive
- Debugger.setBreakpointByUrl
- Debugger.pause
- Debugger.removeBreakpoint
- Debugger.resume
- Debugger.stepInto
- Debugger.stepOut
- Debugger.stepOver
- Runtime.enable
- Runtime.evaluate
- Runtime.callFunctionOn
- Runtime.getProperties
- Runtime.releaseObject
- Overlay.setPausedInDebuggerMessage

Or, implementing your own dev tools panel is a choice as well, although it may be a tough work.

But, unfortunately we don't have the ability of communicating with the browser internal dev tools, in case of using vanilla JS.
